
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 91859
 */
public class seatalloc extends javax.swing.JFrame {
     Connection conn=null;
PreparedStatement stmt=null;
ResultSet rs=null;
Statement st=null;
    String[] rooms=new String[20];
    String[] dept=new String[15];
    int[][] arrange=new int[500][10];
    int n,m,flag;
    int bench;
    /**
     * Creates new form seatalloc
     */
    public seatalloc() {
        initComponents();
    }
public void select(){
    int i=0;
        if(c1.isSelected()){
            rooms[i]="411";
            i++;
        }if(c2.isSelected()){
            rooms[i]="412";
            i++;
        }if(c3.isSelected()){
            rooms[i]="413";
            i++;
        }if(c4.isSelected()){
            rooms[i]="422";
            i++;
        }if(c5.isSelected()){
            rooms[i]="202";
            i++;
        }if(c6.isSelected()){
            rooms[i]="201";
            i++;
        }if(c7.isSelected()){
            rooms[i]="601";
            i++;
        }if(c8.isSelected()){
            rooms[i]="603";
            i++;
        }
        if(c9.isSelected()){
            rooms[i]="604";
            i++;
        }
        if(c10.isSelected()){
            rooms[i]="605";
            i++;
        }
        if(c11.isSelected()){
            rooms[i]="Drawing hall";
            i++;
        }
        n=i;
        for(i=0;i<n;i++){
            System.out.println(rooms[i]);
        }
        
        i=0;
        if(y1.isSelected()){
            dept[i]="S1CS";
            i++;
        }if(y2.isSelected()){
            dept[i]="S1EC";
            i++;
        }if(y3.isSelected()){
            dept[i]="S1EEE";
            i++;
        }
        if(y4.isSelected()){
            dept[i]="S3CS";
            i++;
        }
        if(y5.isSelected()){
            dept[i]="S3EC";
            i++;
        }if(y6.isSelected()){
            dept[i]="S3EEE";
            i++;
        }if(y7.isSelected()){
            dept[i]="S5CSA";
            i++;
            dept[i]="S3CSB";
            i++;
        }if(y8.isSelected()){
            dept[i]="S5EC";
            i++;
        }
        if(y9.isSelected()){
            dept[i]="S5EEE";
            i++;
        }
        if(y10.isSelected()){
            dept[i]="S7CS";
            i++;
        }
        if(y11.isSelected()){
            dept[i]="S7EC";
            i++;
        }if(y12.isSelected()){
            dept[i]="S7EEE";
            i++;
        }
        m=i;
        for(i=0;i<m;i++){
            System.out.println(dept[i]);
        }
}
         public void NoOfBench(){
    String url ="jdbc:mysql://localhost:3306/project";
    bench=0;        
    try {
            String uname="root";
            String password="archana@2002";
            Connection conn = DriverManager.getConnection(url,uname,password);
                Statement st = conn.createStatement();
                String sql1="SELECT * FROM room";
                PreparedStatement pst=conn.prepareStatement(sql1);
                ResultSet rs=pst.executeQuery(sql1);
                while(rs.next()){
                    int i=0;
                    while(i<n){
                        String s=rs.getString(1);
                        if(rooms[i].equals(s)){
                            bench=bench+Integer.parseInt(rs.getString(2));
                            break;
                        }
                        i++;
                    }
                }
                System.out.println("No Of Benches"+bench);
            }catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
        }    
}

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c9 = new javax.swing.JCheckBox();
        c10 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c11 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        y2 = new javax.swing.JCheckBox();
        y1 = new javax.swing.JCheckBox();
        y3 = new javax.swing.JCheckBox();
        y4 = new javax.swing.JCheckBox();
        y5 = new javax.swing.JCheckBox();
        y6 = new javax.swing.JCheckBox();
        y7 = new javax.swing.JCheckBox();
        y9 = new javax.swing.JCheckBox();
        y8 = new javax.swing.JCheckBox();
        y10 = new javax.swing.JCheckBox();
        y12 = new javax.swing.JCheckBox();
        y11 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel1.setText("ROOM USED");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLASSES");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        c1.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        c1.setText("411");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        c2.setFont(c1.getFont());
        c2.setText("412");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c3.setFont(c2.getFont());
        c3.setText("413");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c4.setFont(c2.getFont());
        c4.setText("422");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });

        c8.setFont(c2.getFont());
        c8.setText("603");
        c8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c8ActionPerformed(evt);
            }
        });

        c9.setFont(c2.getFont());
        c9.setText("604");
        c9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c9ActionPerformed(evt);
            }
        });

        c10.setFont(c2.getFont());
        c10.setText("605");
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });

        c7.setFont(c2.getFont());
        c7.setText("601");
        c7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c7ActionPerformed(evt);
            }
        });

        c6.setFont(c2.getFont());
        c6.setText("201");
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });

        c11.setFont(c1.getFont());
        c11.setText("DRAWING HALL");
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });

        c5.setFont(c2.getFont());
        c5.setText("202");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        y2.setFont(c2.getFont());
        y2.setText("1stEC");
        y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2ActionPerformed(evt);
            }
        });

        y1.setFont(c2.getFont());
        y1.setText("1stCS");
        y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1ActionPerformed(evt);
            }
        });

        y3.setText("1stEEE");
        y3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3ActionPerformed(evt);
            }
        });

        y4.setText("2ndCS");
        y4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y4ActionPerformed(evt);
            }
        });

        y5.setText("2ndEC");
        y5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y5ActionPerformed(evt);
            }
        });

        y6.setText("2ndEEE");
        y6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y6ActionPerformed(evt);
            }
        });

        y7.setText("3rdCS");
        y7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y7ActionPerformed(evt);
            }
        });

        y9.setText("3rdEEE");
        y9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y9ActionPerformed(evt);
            }
        });

        y8.setText("3rdEC");
        y8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y8ActionPerformed(evt);
            }
        });

        y10.setText("4thCS");
        y10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y10ActionPerformed(evt);
            }
        });

        y12.setText("4thEEE");
        y12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y12ActionPerformed(evt);
            }
        });

        y11.setText("4thEC");
        y11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y11ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jButton1.setText("ARRANGE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jButton2.setText("VIEW ARRANGEMENT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c8)
                            .addComponent(c1)
                            .addComponent(c6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c2)
                                .addGap(18, 18, 18)
                                .addComponent(c3)
                                .addGap(18, 18, 18)
                                .addComponent(c4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c5)
                                .addGap(18, 18, 18)
                                .addComponent(c11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c9)
                                .addGap(18, 18, 18)
                                .addComponent(c10)
                                .addGap(18, 18, 18)
                                .addComponent(c7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1)))
                .addGap(63, 63, 63)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(y10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(y11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(y7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(y8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(y4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(y5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(y1)
                                        .addGap(41, 41, 41)
                                        .addComponent(y2)))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(y3)
                                    .addComponent(y6)
                                    .addComponent(y9)
                                    .addComponent(y12))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c1)
                                    .addComponent(c2)
                                    .addComponent(c3)
                                    .addComponent(c4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c8)
                                    .addComponent(c9)
                                    .addComponent(c10)
                                    .addComponent(c7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c6)
                                    .addComponent(c11)
                                    .addComponent(c5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y2)
                                    .addComponent(y3)
                                    .addComponent(y1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y4)
                                    .addComponent(y5)
                                    .addComponent(y6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(y7)
                                    .addComponent(y9)
                                    .addComponent(y8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y10)
                                    .addComponent(y11)
                                    .addComponent(y12)))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c8ActionPerformed

    private void c9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c9ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void c7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c7ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c5ActionPerformed

    private void y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2ActionPerformed

    private void y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1ActionPerformed

    private void y3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3ActionPerformed

    private void y4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y4ActionPerformed

    private void y5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y5ActionPerformed

    private void y6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y6ActionPerformed

    private void y7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y7ActionPerformed

    private void y9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y9ActionPerformed

    private void y8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y8ActionPerformed

    private void y10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y10ActionPerformed

    private void y12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y12ActionPerformed

    private void y11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         select();
            NoOfBench();
            try  {
                String url="jdbc:mysql://localhost:3306/project";
            String uname="root";
            String password="archana@2002";
            Connection conn = DriverManager.getConnection(url,uname,password);
                Statement st = conn.createStatement();
                String sql1="SELECT * FROM student"; 
                ResultSet rs=st.executeQuery(sql1);
                int i=0;
                int c=0;
                do{
                    for(int j=0;j<bench;j++){
                        if(rs.next()){
                            for(int d=0;d<m;d++){
                                if (dept[d].equalsIgnoreCase(rs.getString(4))){
                                    arrange[j][i]=rs.getInt(1);
                                    break;
                                }
                            }
                            if(arrange[j][i]==0){
                                j--;
                            }
                        }
                        else{
                            c=1;
                            break;
                        }
                    }
                    i++;
                }while(c==0);
                flag=i;
                if(i>3){
                        JOptionPane.showMessageDialog(null, "arrangement not possible");
                    }
                for(int k=0;k<bench;k++){
                    for(int j=0;j<flag;j++){
                        System.out.print(arrange[k][j]+"    ");
                    }
                    System.out.println("");
                }
                viewalloc v=new viewalloc(arrange, rooms, bench);                              
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        viewalloc v= new viewalloc();
        v.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seatalloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seatalloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seatalloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seatalloc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seatalloc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c10;
    private javax.swing.JCheckBox c11;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox y1;
    private javax.swing.JCheckBox y10;
    private javax.swing.JCheckBox y11;
    private javax.swing.JCheckBox y12;
    private javax.swing.JCheckBox y2;
    private javax.swing.JCheckBox y3;
    private javax.swing.JCheckBox y4;
    private javax.swing.JCheckBox y5;
    private javax.swing.JCheckBox y6;
    private javax.swing.JCheckBox y7;
    private javax.swing.JCheckBox y8;
    private javax.swing.JCheckBox y9;
    // End of variables declaration//GEN-END:variables
}
